// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
    user_id,
    exposed_table_id,
    operation_type,
    row_identifier,
    changed_data,
    ip_address,
    user_agent
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, exposed_table_id, operation_type, row_identifier, changed_data, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	UserID         sql.NullInt64
	ExposedTableID sql.NullInt64
	OperationType  string
	RowIdentifier  sql.NullString
	ChangedData    sql.NullString
	IpAddress      sql.NullString
	UserAgent      sql.NullString
}

// Audit Logs queries
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserID,
		arg.ExposedTableID,
		arg.OperationType,
		arg.RowIdentifier,
		arg.ChangedData,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.OperationType,
		&i.RowIdentifier,
		&i.ChangedData,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :exec
DELETE FROM audit_logs
WHERE created_at < ?
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldAuditLogs, createdAt)
	return err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, user_id, exposed_table_id, operation_type, row_identifier, changed_data, ip_address, user_agent, created_at
FROM audit_logs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAuditLog(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.OperationType,
		&i.RowIdentifier,
		&i.ChangedData,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByDateRange = `-- name: ListAuditLogsByDateRange :many
SELECT id, user_id, exposed_table_id, operation_type, row_identifier, changed_data, ip_address, user_agent, created_at
FROM audit_logs
WHERE created_at >= ? AND created_at <= ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByDateRangeParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int64
	Offset      int64
}

func (q *Queries) ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.OperationType,
			&i.RowIdentifier,
			&i.ChangedData,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByOperation = `-- name: ListAuditLogsByOperation :many
SELECT id, user_id, exposed_table_id, operation_type, row_identifier, changed_data, ip_address, user_agent, created_at
FROM audit_logs
WHERE operation_type = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByOperationParams struct {
	OperationType string
	Limit         int64
	Offset        int64
}

func (q *Queries) ListAuditLogsByOperation(ctx context.Context, arg ListAuditLogsByOperationParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByOperation, arg.OperationType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.OperationType,
			&i.RowIdentifier,
			&i.ChangedData,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTable = `-- name: ListAuditLogsByTable :many
SELECT id, user_id, exposed_table_id, operation_type, row_identifier, changed_data, ip_address, user_agent, created_at
FROM audit_logs
WHERE exposed_table_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByTableParams struct {
	ExposedTableID sql.NullInt64
	Limit          int64
	Offset         int64
}

func (q *Queries) ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByTable, arg.ExposedTableID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.OperationType,
			&i.RowIdentifier,
			&i.ChangedData,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, exposed_table_id, operation_type, row_identifier, changed_data, ip_address, user_agent, created_at
FROM audit_logs
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByUserParams struct {
	UserID sql.NullInt64
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.OperationType,
			&i.RowIdentifier,
			&i.ChangedData,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
