// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package store

import (
	"context"
	"database/sql"
)

const createConnection = `-- name: CreateConnection :one

INSERT INTO connections (
    name,
    host,
    port,
    database,
    username,
    encrypted_password,
    ssl_mode,
    ssl_config
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, host, port, "database", username, encrypted_password, ssl_mode, ssl_config, is_active, created_at, updated_at
`

type CreateConnectionParams struct {
	Name              string
	Host              string
	Port              int64
	Database          string
	Username          string
	EncryptedPassword string
	SslMode           string
	SslConfig         sql.NullString
}

// Connection Management queries
func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Database,
		arg.Username,
		arg.EncryptedPassword,
		arg.SslMode,
		arg.SslConfig,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Database,
		&i.Username,
		&i.EncryptedPassword,
		&i.SslMode,
		&i.SslConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections
WHERE id = ?
`

func (q *Queries) DeleteConnection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, name, host, port, "database", username, encrypted_password, ssl_mode, ssl_config, is_active, created_at, updated_at
FROM connections
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetConnection(ctx context.Context, id int64) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Database,
		&i.Username,
		&i.EncryptedPassword,
		&i.SslMode,
		&i.SslConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionByName = `-- name: GetConnectionByName :one
SELECT id, name, host, port, "database", username, encrypted_password, ssl_mode, ssl_config, is_active, created_at, updated_at
FROM connections
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetConnectionByName(ctx context.Context, name string) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionByName, name)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Database,
		&i.Username,
		&i.EncryptedPassword,
		&i.SslMode,
		&i.SslConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveConnections = `-- name: ListActiveConnections :many
SELECT id, name, host, port, "database", username, encrypted_password, ssl_mode, ssl_config, is_active, created_at, updated_at
FROM connections
WHERE is_active = 1
ORDER BY created_at DESC
`

func (q *Queries) ListActiveConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listActiveConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Database,
			&i.Username,
			&i.EncryptedPassword,
			&i.SslMode,
			&i.SslConfig,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT id, name, host, port, "database", username, encrypted_password, ssl_mode, ssl_config, is_active, created_at, updated_at
FROM connections
ORDER BY created_at DESC
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Database,
			&i.Username,
			&i.EncryptedPassword,
			&i.SslMode,
			&i.SslConfig,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE connections
SET 
    name = ?,
    host = ?,
    port = ?,
    database = ?,
    username = ?,
    encrypted_password = ?,
    ssl_mode = ?,
    ssl_config = ?
WHERE id = ?
RETURNING id, name, host, port, "database", username, encrypted_password, ssl_mode, ssl_config, is_active, created_at, updated_at
`

type UpdateConnectionParams struct {
	Name              string
	Host              string
	Port              int64
	Database          string
	Username          string
	EncryptedPassword string
	SslMode           string
	SslConfig         sql.NullString
	ID                int64
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, updateConnection,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Database,
		arg.Username,
		arg.EncryptedPassword,
		arg.SslMode,
		arg.SslConfig,
		arg.ID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Database,
		&i.Username,
		&i.EncryptedPassword,
		&i.SslMode,
		&i.SslConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE connections
SET is_active = ?
WHERE id = ?
`

type UpdateConnectionStatusParams struct {
	IsActive int64
	ID       int64
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateConnectionStatus, arg.IsActive, arg.ID)
	return err
}
