// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exposed_tables.sql

package store

import (
	"context"
	"database/sql"
)

const createExposedTable = `-- name: CreateExposedTable :one

INSERT INTO exposed_tables (
    connection_id,
    schema_name,
    table_name,
    display_name,
    description,
    is_active
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, connection_id, schema_name, table_name, display_name, description, is_active, created_at, updated_at
`

type CreateExposedTableParams struct {
	ConnectionID int64
	SchemaName   string
	TableName    string
	DisplayName  string
	Description  sql.NullString
	IsActive     int64
}

// Exposed Tables queries
func (q *Queries) CreateExposedTable(ctx context.Context, arg CreateExposedTableParams) (ExposedTable, error) {
	row := q.db.QueryRowContext(ctx, createExposedTable,
		arg.ConnectionID,
		arg.SchemaName,
		arg.TableName,
		arg.DisplayName,
		arg.Description,
		arg.IsActive,
	)
	var i ExposedTable
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.SchemaName,
		&i.TableName,
		&i.DisplayName,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExposedTable = `-- name: DeleteExposedTable :exec
DELETE FROM exposed_tables
WHERE id = ?
`

func (q *Queries) DeleteExposedTable(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExposedTable, id)
	return err
}

const deleteExposedTablesByConnection = `-- name: DeleteExposedTablesByConnection :exec
DELETE FROM exposed_tables
WHERE connection_id = ?
`

func (q *Queries) DeleteExposedTablesByConnection(ctx context.Context, connectionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteExposedTablesByConnection, connectionID)
	return err
}

const getExposedTable = `-- name: GetExposedTable :one
SELECT id, connection_id, schema_name, table_name, display_name, description, is_active, created_at, updated_at
FROM exposed_tables
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetExposedTable(ctx context.Context, id int64) (ExposedTable, error) {
	row := q.db.QueryRowContext(ctx, getExposedTable, id)
	var i ExposedTable
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.SchemaName,
		&i.TableName,
		&i.DisplayName,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveExposedTablesByConnection = `-- name: ListActiveExposedTablesByConnection :many
SELECT id, connection_id, schema_name, table_name, display_name, description, is_active, created_at, updated_at
FROM exposed_tables
WHERE connection_id = ? AND is_active = 1
ORDER BY display_name
`

func (q *Queries) ListActiveExposedTablesByConnection(ctx context.Context, connectionID int64) ([]ExposedTable, error) {
	rows, err := q.db.QueryContext(ctx, listActiveExposedTablesByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposedTable
	for rows.Next() {
		var i ExposedTable
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SchemaName,
			&i.TableName,
			&i.DisplayName,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposedTablesByConnection = `-- name: ListExposedTablesByConnection :many
SELECT id, connection_id, schema_name, table_name, display_name, description, is_active, created_at, updated_at
FROM exposed_tables
WHERE connection_id = ?
ORDER BY display_name
`

func (q *Queries) ListExposedTablesByConnection(ctx context.Context, connectionID int64) ([]ExposedTable, error) {
	rows, err := q.db.QueryContext(ctx, listExposedTablesByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposedTable
	for rows.Next() {
		var i ExposedTable
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SchemaName,
			&i.TableName,
			&i.DisplayName,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExposedTable = `-- name: UpdateExposedTable :one
UPDATE exposed_tables
SET 
    display_name = ?,
    description = ?,
    is_active = ?
WHERE id = ?
RETURNING id, connection_id, schema_name, table_name, display_name, description, is_active, created_at, updated_at
`

type UpdateExposedTableParams struct {
	DisplayName string
	Description sql.NullString
	IsActive    int64
	ID          int64
}

func (q *Queries) UpdateExposedTable(ctx context.Context, arg UpdateExposedTableParams) (ExposedTable, error) {
	row := q.db.QueryRowContext(ctx, updateExposedTable,
		arg.DisplayName,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i ExposedTable
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.SchemaName,
		&i.TableName,
		&i.DisplayName,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
