// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exposed_columns.sql

package store

import (
	"context"
	"database/sql"
)

const createExposedColumn = `-- name: CreateExposedColumn :one

INSERT INTO exposed_columns (
    exposed_table_id,
    column_name,
    display_name,
    data_type,
    is_visible,
    is_editable,
    display_order,
    validation_rules
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, exposed_table_id, column_name, display_name, data_type, is_visible, is_editable, display_order, validation_rules, created_at, updated_at
`

type CreateExposedColumnParams struct {
	ExposedTableID  int64
	ColumnName      string
	DisplayName     string
	DataType        string
	IsVisible       int64
	IsEditable      int64
	DisplayOrder    int64
	ValidationRules sql.NullString
}

// Exposed Columns queries
func (q *Queries) CreateExposedColumn(ctx context.Context, arg CreateExposedColumnParams) (ExposedColumn, error) {
	row := q.db.QueryRowContext(ctx, createExposedColumn,
		arg.ExposedTableID,
		arg.ColumnName,
		arg.DisplayName,
		arg.DataType,
		arg.IsVisible,
		arg.IsEditable,
		arg.DisplayOrder,
		arg.ValidationRules,
	)
	var i ExposedColumn
	err := row.Scan(
		&i.ID,
		&i.ExposedTableID,
		&i.ColumnName,
		&i.DisplayName,
		&i.DataType,
		&i.IsVisible,
		&i.IsEditable,
		&i.DisplayOrder,
		&i.ValidationRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExposedColumn = `-- name: DeleteExposedColumn :exec
DELETE FROM exposed_columns
WHERE id = ?
`

func (q *Queries) DeleteExposedColumn(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExposedColumn, id)
	return err
}

const deleteExposedColumnsByTable = `-- name: DeleteExposedColumnsByTable :exec
DELETE FROM exposed_columns
WHERE exposed_table_id = ?
`

func (q *Queries) DeleteExposedColumnsByTable(ctx context.Context, exposedTableID int64) error {
	_, err := q.db.ExecContext(ctx, deleteExposedColumnsByTable, exposedTableID)
	return err
}

const getExposedColumn = `-- name: GetExposedColumn :one
SELECT id, exposed_table_id, column_name, display_name, data_type, is_visible, is_editable, display_order, validation_rules, created_at, updated_at
FROM exposed_columns
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetExposedColumn(ctx context.Context, id int64) (ExposedColumn, error) {
	row := q.db.QueryRowContext(ctx, getExposedColumn, id)
	var i ExposedColumn
	err := row.Scan(
		&i.ID,
		&i.ExposedTableID,
		&i.ColumnName,
		&i.DisplayName,
		&i.DataType,
		&i.IsVisible,
		&i.IsEditable,
		&i.DisplayOrder,
		&i.ValidationRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExposedColumnsByTable = `-- name: ListExposedColumnsByTable :many
SELECT id, exposed_table_id, column_name, display_name, data_type, is_visible, is_editable, display_order, validation_rules, created_at, updated_at
FROM exposed_columns
WHERE exposed_table_id = ?
ORDER BY display_order, column_name
`

func (q *Queries) ListExposedColumnsByTable(ctx context.Context, exposedTableID int64) ([]ExposedColumn, error) {
	rows, err := q.db.QueryContext(ctx, listExposedColumnsByTable, exposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposedColumn
	for rows.Next() {
		var i ExposedColumn
		if err := rows.Scan(
			&i.ID,
			&i.ExposedTableID,
			&i.ColumnName,
			&i.DisplayName,
			&i.DataType,
			&i.IsVisible,
			&i.IsEditable,
			&i.DisplayOrder,
			&i.ValidationRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleColumnsByTable = `-- name: ListVisibleColumnsByTable :many
SELECT id, exposed_table_id, column_name, display_name, data_type, is_visible, is_editable, display_order, validation_rules, created_at, updated_at
FROM exposed_columns
WHERE exposed_table_id = ? AND is_visible = 1
ORDER BY display_order, column_name
`

func (q *Queries) ListVisibleColumnsByTable(ctx context.Context, exposedTableID int64) ([]ExposedColumn, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleColumnsByTable, exposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposedColumn
	for rows.Next() {
		var i ExposedColumn
		if err := rows.Scan(
			&i.ID,
			&i.ExposedTableID,
			&i.ColumnName,
			&i.DisplayName,
			&i.DataType,
			&i.IsVisible,
			&i.IsEditable,
			&i.DisplayOrder,
			&i.ValidationRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExposedColumn = `-- name: UpdateExposedColumn :one
UPDATE exposed_columns
SET 
    display_name = ?,
    is_visible = ?,
    is_editable = ?,
    display_order = ?,
    validation_rules = ?
WHERE id = ?
RETURNING id, exposed_table_id, column_name, display_name, data_type, is_visible, is_editable, display_order, validation_rules, created_at, updated_at
`

type UpdateExposedColumnParams struct {
	DisplayName     string
	IsVisible       int64
	IsEditable      int64
	DisplayOrder    int64
	ValidationRules sql.NullString
	ID              int64
}

func (q *Queries) UpdateExposedColumn(ctx context.Context, arg UpdateExposedColumnParams) (ExposedColumn, error) {
	row := q.db.QueryRowContext(ctx, updateExposedColumn,
		arg.DisplayName,
		arg.IsVisible,
		arg.IsEditable,
		arg.DisplayOrder,
		arg.ValidationRules,
		arg.ID,
	)
	var i ExposedColumn
	err := row.Scan(
		&i.ID,
		&i.ExposedTableID,
		&i.ColumnName,
		&i.DisplayName,
		&i.DataType,
		&i.IsVisible,
		&i.IsEditable,
		&i.DisplayOrder,
		&i.ValidationRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
