// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package store

import (
	"context"
)

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (
    role_id,
    exposed_table_id,
    can_view,
    can_create,
    can_update,
    can_delete
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, role_id, exposed_table_id, can_view, can_create, can_update, can_delete, created_at, updated_at
`

type CreatePermissionParams struct {
	RoleID         int64
	ExposedTableID int64
	CanView        int64
	CanCreate      int64
	CanUpdate      int64
	CanDelete      int64
}

// Permissions queries
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission,
		arg.RoleID,
		arg.ExposedTableID,
		arg.CanView,
		arg.CanCreate,
		arg.CanUpdate,
		arg.CanDelete,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ExposedTableID,
		&i.CanView,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRLSRule = `-- name: CreateRLSRule :one

INSERT INTO row_level_security_rules (
    exposed_table_id,
    role_id,
    rule_name,
    filter_expression,
    is_active
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, exposed_table_id, role_id, rule_name, filter_expression, is_active, created_at, updated_at
`

type CreateRLSRuleParams struct {
	ExposedTableID   int64
	RoleID           int64
	RuleName         string
	FilterExpression string
	IsActive         int64
}

// Row-Level Security Rules queries
func (q *Queries) CreateRLSRule(ctx context.Context, arg CreateRLSRuleParams) (RowLevelSecurityRule, error) {
	row := q.db.QueryRowContext(ctx, createRLSRule,
		arg.ExposedTableID,
		arg.RoleID,
		arg.RuleName,
		arg.FilterExpression,
		arg.IsActive,
	)
	var i RowLevelSecurityRule
	err := row.Scan(
		&i.ID,
		&i.ExposedTableID,
		&i.RoleID,
		&i.RuleName,
		&i.FilterExpression,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE id = ?
`

func (q *Queries) DeletePermission(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const deletePermissionsByRole = `-- name: DeletePermissionsByRole :exec
DELETE FROM permissions
WHERE role_id = ?
`

func (q *Queries) DeletePermissionsByRole(ctx context.Context, roleID int64) error {
	_, err := q.db.ExecContext(ctx, deletePermissionsByRole, roleID)
	return err
}

const deletePermissionsByTable = `-- name: DeletePermissionsByTable :exec
DELETE FROM permissions
WHERE exposed_table_id = ?
`

func (q *Queries) DeletePermissionsByTable(ctx context.Context, exposedTableID int64) error {
	_, err := q.db.ExecContext(ctx, deletePermissionsByTable, exposedTableID)
	return err
}

const deleteRLSRule = `-- name: DeleteRLSRule :exec
DELETE FROM row_level_security_rules
WHERE id = ?
`

func (q *Queries) DeleteRLSRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRLSRule, id)
	return err
}

const deleteRLSRulesByRole = `-- name: DeleteRLSRulesByRole :exec
DELETE FROM row_level_security_rules
WHERE role_id = ?
`

func (q *Queries) DeleteRLSRulesByRole(ctx context.Context, roleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRLSRulesByRole, roleID)
	return err
}

const deleteRLSRulesByTable = `-- name: DeleteRLSRulesByTable :exec
DELETE FROM row_level_security_rules
WHERE exposed_table_id = ?
`

func (q *Queries) DeleteRLSRulesByTable(ctx context.Context, exposedTableID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRLSRulesByTable, exposedTableID)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT id, role_id, exposed_table_id, can_view, can_create, can_update, can_delete, created_at, updated_at
FROM permissions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPermission(ctx context.Context, id int64) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ExposedTableID,
		&i.CanView,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByRoleAndTable = `-- name: GetPermissionByRoleAndTable :one
SELECT id, role_id, exposed_table_id, can_view, can_create, can_update, can_delete, created_at, updated_at
FROM permissions
WHERE role_id = ? AND exposed_table_id = ?
LIMIT 1
`

type GetPermissionByRoleAndTableParams struct {
	RoleID         int64
	ExposedTableID int64
}

func (q *Queries) GetPermissionByRoleAndTable(ctx context.Context, arg GetPermissionByRoleAndTableParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByRoleAndTable, arg.RoleID, arg.ExposedTableID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ExposedTableID,
		&i.CanView,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRLSRule = `-- name: GetRLSRule :one
SELECT id, exposed_table_id, role_id, rule_name, filter_expression, is_active, created_at, updated_at
FROM row_level_security_rules
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetRLSRule(ctx context.Context, id int64) (RowLevelSecurityRule, error) {
	row := q.db.QueryRowContext(ctx, getRLSRule, id)
	var i RowLevelSecurityRule
	err := row.Scan(
		&i.ID,
		&i.ExposedTableID,
		&i.RoleID,
		&i.RuleName,
		&i.FilterExpression,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRLSRulesByTableAndRole = `-- name: ListActiveRLSRulesByTableAndRole :many
SELECT id, exposed_table_id, role_id, rule_name, filter_expression, is_active, created_at, updated_at
FROM row_level_security_rules
WHERE exposed_table_id = ? AND role_id = ? AND is_active = 1
ORDER BY rule_name
`

type ListActiveRLSRulesByTableAndRoleParams struct {
	ExposedTableID int64
	RoleID         int64
}

func (q *Queries) ListActiveRLSRulesByTableAndRole(ctx context.Context, arg ListActiveRLSRulesByTableAndRoleParams) ([]RowLevelSecurityRule, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRLSRulesByTableAndRole, arg.ExposedTableID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowLevelSecurityRule
	for rows.Next() {
		var i RowLevelSecurityRule
		if err := rows.Scan(
			&i.ID,
			&i.ExposedTableID,
			&i.RoleID,
			&i.RuleName,
			&i.FilterExpression,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT id, role_id, exposed_table_id, can_view, can_create, can_update, can_delete, created_at, updated_at
FROM permissions
WHERE role_id = ?
ORDER BY exposed_table_id
`

func (q *Queries) ListPermissionsByRole(ctx context.Context, roleID int64) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ExposedTableID,
			&i.CanView,
			&i.CanCreate,
			&i.CanUpdate,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByTable = `-- name: ListPermissionsByTable :many
SELECT id, role_id, exposed_table_id, can_view, can_create, can_update, can_delete, created_at, updated_at
FROM permissions
WHERE exposed_table_id = ?
ORDER BY role_id
`

func (q *Queries) ListPermissionsByTable(ctx context.Context, exposedTableID int64) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByTable, exposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ExposedTableID,
			&i.CanView,
			&i.CanCreate,
			&i.CanUpdate,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRLSRulesByRole = `-- name: ListRLSRulesByRole :many
SELECT id, exposed_table_id, role_id, rule_name, filter_expression, is_active, created_at, updated_at
FROM row_level_security_rules
WHERE role_id = ?
ORDER BY rule_name
`

func (q *Queries) ListRLSRulesByRole(ctx context.Context, roleID int64) ([]RowLevelSecurityRule, error) {
	rows, err := q.db.QueryContext(ctx, listRLSRulesByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowLevelSecurityRule
	for rows.Next() {
		var i RowLevelSecurityRule
		if err := rows.Scan(
			&i.ID,
			&i.ExposedTableID,
			&i.RoleID,
			&i.RuleName,
			&i.FilterExpression,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRLSRulesByTable = `-- name: ListRLSRulesByTable :many
SELECT id, exposed_table_id, role_id, rule_name, filter_expression, is_active, created_at, updated_at
FROM row_level_security_rules
WHERE exposed_table_id = ?
ORDER BY rule_name
`

func (q *Queries) ListRLSRulesByTable(ctx context.Context, exposedTableID int64) ([]RowLevelSecurityRule, error) {
	rows, err := q.db.QueryContext(ctx, listRLSRulesByTable, exposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowLevelSecurityRule
	for rows.Next() {
		var i RowLevelSecurityRule
		if err := rows.Scan(
			&i.ID,
			&i.ExposedTableID,
			&i.RoleID,
			&i.RuleName,
			&i.FilterExpression,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET 
    can_view = ?,
    can_create = ?,
    can_update = ?,
    can_delete = ?
WHERE id = ?
RETURNING id, role_id, exposed_table_id, can_view, can_create, can_update, can_delete, created_at, updated_at
`

type UpdatePermissionParams struct {
	CanView   int64
	CanCreate int64
	CanUpdate int64
	CanDelete int64
	ID        int64
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, updatePermission,
		arg.CanView,
		arg.CanCreate,
		arg.CanUpdate,
		arg.CanDelete,
		arg.ID,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ExposedTableID,
		&i.CanView,
		&i.CanCreate,
		&i.CanUpdate,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRLSRule = `-- name: UpdateRLSRule :one
UPDATE row_level_security_rules
SET 
    rule_name = ?,
    filter_expression = ?,
    is_active = ?
WHERE id = ?
RETURNING id, exposed_table_id, role_id, rule_name, filter_expression, is_active, created_at, updated_at
`

type UpdateRLSRuleParams struct {
	RuleName         string
	FilterExpression string
	IsActive         int64
	ID               int64
}

func (q *Queries) UpdateRLSRule(ctx context.Context, arg UpdateRLSRuleParams) (RowLevelSecurityRule, error) {
	row := q.db.QueryRowContext(ctx, updateRLSRule,
		arg.RuleName,
		arg.FilterExpression,
		arg.IsActive,
		arg.ID,
	)
	var i RowLevelSecurityRule
	err := row.Scan(
		&i.ID,
		&i.ExposedTableID,
		&i.RoleID,
		&i.RuleName,
		&i.FilterExpression,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
