// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFullSchemaDetails = `-- name: GetFullSchemaDetails :many
SELECT
    n.nspname AS table_schema,
    c.relname AS table_name,
    a.rolname AS table_owner,
    -- reltuples is a float4, so we cast to bigint for a clean integer count.
    c.reltuples::bigint AS estimated_row_count,
    c.relrowsecurity AS row_security_enabled,
    -- A window function to count tables per schema without a separate query.
    COUNT(*) OVER (PARTITION BY n.nspname) AS schema_table_count
FROM
    pg_class c
    JOIN
    pg_namespace n ON n.oid = c.relnamespace
    JOIN
    pg_authid a ON a.oid = c.relowner
ORDER BY
    n.nspname, c.relname
`

type GetFullSchemaDetailsRow struct {
	TableSchema        string
	TableName          string
	TableOwner         string
	EstimatedRowCount  pgtype.Int8
	RowSecurityEnabled bool
	SchemaTableCount   pgtype.Int8
}

// Fetches a complete overview of all schemas and their tables, including ownership
// and row estimates. This single query powers both the sidebar navigation and the
// "Details" tab for any selected table.
func (q *Queries) GetFullSchemaDetails(ctx context.Context) ([]GetFullSchemaDetailsRow, error) {
	rows, err := q.db.Query(ctx, getFullSchemaDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullSchemaDetailsRow
	for rows.Next() {
		var i GetFullSchemaDetailsRow
		if err := rows.Scan(
			&i.TableSchema,
			&i.TableName,
			&i.TableOwner,
			&i.EstimatedRowCount,
			&i.RowSecurityEnabled,
			&i.SchemaTableCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableColumns = `-- name: GetTableColumns :many

SELECT
    column_name,
    data_type,
    -- Present is_nullable as a boolean for easier use in Go.
    CASE WHEN is_nullable = 'YES' THEN true ELSE false END AS is_nullable,
    column_default
FROM
    information_schema.columns
WHERE
    table_schema = $1
    AND table_name = $2
ORDER BY
    ordinal_position
`

type GetTableColumnsParams struct {
	TableSchema pgtype.Text
	TableName   pgtype.Text
}

type GetTableColumnsRow struct {
	ColumnName    interface{}
	DataType      interface{}
	IsNullable    bool
	ColumnDefault interface{}
}

// -
// Retrieves detailed information about each column in a specific table for the "Columns" tab.
func (q *Queries) GetTableColumns(ctx context.Context, arg GetTableColumnsParams) ([]GetTableColumnsRow, error) {
	rows, err := q.db.Query(ctx, getTableColumns, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableColumnsRow
	for rows.Next() {
		var i GetTableColumnsRow
		if err := rows.Scan(
			&i.ColumnName,
			&i.DataType,
			&i.IsNullable,
			&i.ColumnDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableIndexes = `-- name: GetTableIndexes :many

SELECT
    indexname,
    indexdef
FROM
    pg_indexes
WHERE
    schemaname = $1
    AND tablename = $2
ORDER BY
    indexname
`

type GetTableIndexesParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Text
}

type GetTableIndexesRow struct {
	Indexname pgtype.Text
	Indexdef  pgtype.Text
}

// -
// Fetches all indexes for a given table. This is a common and useful feature for a database explorer.
func (q *Queries) GetTableIndexes(ctx context.Context, arg GetTableIndexesParams) ([]GetTableIndexesRow, error) {
	rows, err := q.db.Query(ctx, getTableIndexes, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableIndexesRow
	for rows.Next() {
		var i GetTableIndexesRow
		if err := rows.Scan(&i.Indexname, &i.Indexdef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
