// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_filters.sql

package store

import (
	"context"
)

const createSavedFilter = `-- name: CreateSavedFilter :one

INSERT INTO saved_filters (
    user_id,
    exposed_table_id,
    filter_name,
    filter_config,
    is_public
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, user_id, exposed_table_id, filter_name, filter_config, is_public, created_at, updated_at
`

type CreateSavedFilterParams struct {
	UserID         int64
	ExposedTableID int64
	FilterName     string
	FilterConfig   string
	IsPublic       int64
}

// Saved Filters queries
func (q *Queries) CreateSavedFilter(ctx context.Context, arg CreateSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, createSavedFilter,
		arg.UserID,
		arg.ExposedTableID,
		arg.FilterName,
		arg.FilterConfig,
		arg.IsPublic,
	)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.FilterName,
		&i.FilterConfig,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedFilter = `-- name: DeleteSavedFilter :exec
DELETE FROM saved_filters
WHERE id = ?
`

func (q *Queries) DeleteSavedFilter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSavedFilter, id)
	return err
}

const deleteSavedFiltersByTable = `-- name: DeleteSavedFiltersByTable :exec
DELETE FROM saved_filters
WHERE exposed_table_id = ?
`

func (q *Queries) DeleteSavedFiltersByTable(ctx context.Context, exposedTableID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSavedFiltersByTable, exposedTableID)
	return err
}

const deleteSavedFiltersByUser = `-- name: DeleteSavedFiltersByUser :exec
DELETE FROM saved_filters
WHERE user_id = ?
`

func (q *Queries) DeleteSavedFiltersByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSavedFiltersByUser, userID)
	return err
}

const getSavedFilter = `-- name: GetSavedFilter :one
SELECT id, user_id, exposed_table_id, filter_name, filter_config, is_public, created_at, updated_at
FROM saved_filters
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSavedFilter(ctx context.Context, id int64) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, getSavedFilter, id)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.FilterName,
		&i.FilterConfig,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicSavedFiltersByTable = `-- name: ListPublicSavedFiltersByTable :many
SELECT id, user_id, exposed_table_id, filter_name, filter_config, is_public, created_at, updated_at
FROM saved_filters
WHERE exposed_table_id = ? AND is_public = 1
ORDER BY filter_name
`

func (q *Queries) ListPublicSavedFiltersByTable(ctx context.Context, exposedTableID int64) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listPublicSavedFiltersByTable, exposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedFilter
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.FilterName,
			&i.FilterConfig,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFiltersByTable = `-- name: ListSavedFiltersByTable :many
SELECT id, user_id, exposed_table_id, filter_name, filter_config, is_public, created_at, updated_at
FROM saved_filters
WHERE user_id = ? AND exposed_table_id = ?
ORDER BY filter_name
`

type ListSavedFiltersByTableParams struct {
	UserID         int64
	ExposedTableID int64
}

func (q *Queries) ListSavedFiltersByTable(ctx context.Context, arg ListSavedFiltersByTableParams) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFiltersByTable, arg.UserID, arg.ExposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedFilter
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.FilterName,
			&i.FilterConfig,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFiltersByUser = `-- name: ListSavedFiltersByUser :many
SELECT id, user_id, exposed_table_id, filter_name, filter_config, is_public, created_at, updated_at
FROM saved_filters
WHERE user_id = ?
ORDER BY filter_name
`

func (q *Queries) ListSavedFiltersByUser(ctx context.Context, userID int64) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFiltersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedFilter
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.FilterName,
			&i.FilterConfig,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedFilter = `-- name: UpdateSavedFilter :one
UPDATE saved_filters
SET 
    filter_name = ?,
    filter_config = ?,
    is_public = ?
WHERE id = ?
RETURNING id, user_id, exposed_table_id, filter_name, filter_config, is_public, created_at, updated_at
`

type UpdateSavedFilterParams struct {
	FilterName   string
	FilterConfig string
	IsPublic     int64
	ID           int64
}

func (q *Queries) UpdateSavedFilter(ctx context.Context, arg UpdateSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, updateSavedFilter,
		arg.FilterName,
		arg.FilterConfig,
		arg.IsPublic,
		arg.ID,
	)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.FilterName,
		&i.FilterConfig,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
