// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso.sql

package store

import (
	"context"
	"database/sql"
)

const createSSOProvider = `-- name: CreateSSOProvider :one

INSERT INTO sso_providers (
    provider_name,
    provider_type,
    client_id,
    encrypted_client_secret,
    auth_url,
    token_url,
    user_info_url,
    config,
    is_active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, provider_name, provider_type, client_id, encrypted_client_secret, auth_url, token_url, user_info_url, config, is_active, created_at, updated_at
`

type CreateSSOProviderParams struct {
	ProviderName          string
	ProviderType          string
	ClientID              string
	EncryptedClientSecret string
	AuthUrl               sql.NullString
	TokenUrl              sql.NullString
	UserInfoUrl           sql.NullString
	Config                sql.NullString
	IsActive              int64
}

// SSO Providers queries
func (q *Queries) CreateSSOProvider(ctx context.Context, arg CreateSSOProviderParams) (SsoProvider, error) {
	row := q.db.QueryRowContext(ctx, createSSOProvider,
		arg.ProviderName,
		arg.ProviderType,
		arg.ClientID,
		arg.EncryptedClientSecret,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.UserInfoUrl,
		arg.Config,
		arg.IsActive,
	)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.ProviderType,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSSOProvider = `-- name: DeleteSSOProvider :exec
DELETE FROM sso_providers
WHERE id = ?
`

func (q *Queries) DeleteSSOProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSSOProvider, id)
	return err
}

const getSSOProvider = `-- name: GetSSOProvider :one
SELECT id, provider_name, provider_type, client_id, encrypted_client_secret, auth_url, token_url, user_info_url, config, is_active, created_at, updated_at
FROM sso_providers
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSSOProvider(ctx context.Context, id int64) (SsoProvider, error) {
	row := q.db.QueryRowContext(ctx, getSSOProvider, id)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.ProviderType,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOProviderByName = `-- name: GetSSOProviderByName :one
SELECT id, provider_name, provider_type, client_id, encrypted_client_secret, auth_url, token_url, user_info_url, config, is_active, created_at, updated_at
FROM sso_providers
WHERE provider_name = ?
LIMIT 1
`

func (q *Queries) GetSSOProviderByName(ctx context.Context, providerName string) (SsoProvider, error) {
	row := q.db.QueryRowContext(ctx, getSSOProviderByName, providerName)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.ProviderType,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSSOProviders = `-- name: ListActiveSSOProviders :many
SELECT id, provider_name, provider_type, client_id, encrypted_client_secret, auth_url, token_url, user_info_url, config, is_active, created_at, updated_at
FROM sso_providers
WHERE is_active = 1
ORDER BY provider_name
`

func (q *Queries) ListActiveSSOProviders(ctx context.Context) ([]SsoProvider, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoProvider
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderName,
			&i.ProviderType,
			&i.ClientID,
			&i.EncryptedClientSecret,
			&i.AuthUrl,
			&i.TokenUrl,
			&i.UserInfoUrl,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOProviders = `-- name: ListSSOProviders :many
SELECT id, provider_name, provider_type, client_id, encrypted_client_secret, auth_url, token_url, user_info_url, config, is_active, created_at, updated_at
FROM sso_providers
ORDER BY provider_name
`

func (q *Queries) ListSSOProviders(ctx context.Context) ([]SsoProvider, error) {
	rows, err := q.db.QueryContext(ctx, listSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoProvider
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderName,
			&i.ProviderType,
			&i.ClientID,
			&i.EncryptedClientSecret,
			&i.AuthUrl,
			&i.TokenUrl,
			&i.UserInfoUrl,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSSOProvider = `-- name: UpdateSSOProvider :one
UPDATE sso_providers
SET 
    provider_name = ?,
    provider_type = ?,
    client_id = ?,
    encrypted_client_secret = ?,
    auth_url = ?,
    token_url = ?,
    user_info_url = ?,
    config = ?,
    is_active = ?
WHERE id = ?
RETURNING id, provider_name, provider_type, client_id, encrypted_client_secret, auth_url, token_url, user_info_url, config, is_active, created_at, updated_at
`

type UpdateSSOProviderParams struct {
	ProviderName          string
	ProviderType          string
	ClientID              string
	EncryptedClientSecret string
	AuthUrl               sql.NullString
	TokenUrl              sql.NullString
	UserInfoUrl           sql.NullString
	Config                sql.NullString
	IsActive              int64
	ID                    int64
}

func (q *Queries) UpdateSSOProvider(ctx context.Context, arg UpdateSSOProviderParams) (SsoProvider, error) {
	row := q.db.QueryRowContext(ctx, updateSSOProvider,
		arg.ProviderName,
		arg.ProviderType,
		arg.ClientID,
		arg.EncryptedClientSecret,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.UserInfoUrl,
		arg.Config,
		arg.IsActive,
		arg.ID,
	)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.ProviderType,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
