// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_jobs.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const completeUploadJob = `-- name: CompleteUploadJob :exec
UPDATE upload_jobs
SET 
    status = 'completed',
    completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CompleteUploadJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeUploadJob, id)
	return err
}

const createUploadJob = `-- name: CreateUploadJob :one

INSERT INTO upload_jobs (
    user_id,
    exposed_table_id,
    filename,
    row_count,
    status,
    mapping_config
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, exposed_table_id, filename, row_count, status, error_message, mapping_config, created_at, completed_at
`

type CreateUploadJobParams struct {
	UserID         int64
	ExposedTableID int64
	Filename       string
	RowCount       int64
	Status         string
	MappingConfig  sql.NullString
}

// Upload Jobs queries
func (q *Queries) CreateUploadJob(ctx context.Context, arg CreateUploadJobParams) (UploadJob, error) {
	row := q.db.QueryRowContext(ctx, createUploadJob,
		arg.UserID,
		arg.ExposedTableID,
		arg.Filename,
		arg.RowCount,
		arg.Status,
		arg.MappingConfig,
	)
	var i UploadJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.Filename,
		&i.RowCount,
		&i.Status,
		&i.ErrorMessage,
		&i.MappingConfig,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteOldUploadJobs = `-- name: DeleteOldUploadJobs :exec
DELETE FROM upload_jobs
WHERE created_at < ? AND status IN ('completed', 'failed')
`

func (q *Queries) DeleteOldUploadJobs(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldUploadJobs, createdAt)
	return err
}

const deleteUploadJob = `-- name: DeleteUploadJob :exec
DELETE FROM upload_jobs
WHERE id = ?
`

func (q *Queries) DeleteUploadJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUploadJob, id)
	return err
}

const getUploadJob = `-- name: GetUploadJob :one
SELECT id, user_id, exposed_table_id, filename, row_count, status, error_message, mapping_config, created_at, completed_at
FROM upload_jobs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUploadJob(ctx context.Context, id int64) (UploadJob, error) {
	row := q.db.QueryRowContext(ctx, getUploadJob, id)
	var i UploadJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.Filename,
		&i.RowCount,
		&i.Status,
		&i.ErrorMessage,
		&i.MappingConfig,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listUploadJobsByStatus = `-- name: ListUploadJobsByStatus :many
SELECT id, user_id, exposed_table_id, filename, row_count, status, error_message, mapping_config, created_at, completed_at
FROM upload_jobs
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUploadJobsByStatusParams struct {
	Status string
	Limit  int64
	Offset int64
}

func (q *Queries) ListUploadJobsByStatus(ctx context.Context, arg ListUploadJobsByStatusParams) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listUploadJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.Filename,
			&i.RowCount,
			&i.Status,
			&i.ErrorMessage,
			&i.MappingConfig,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadJobsByTable = `-- name: ListUploadJobsByTable :many
SELECT id, user_id, exposed_table_id, filename, row_count, status, error_message, mapping_config, created_at, completed_at
FROM upload_jobs
WHERE exposed_table_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUploadJobsByTableParams struct {
	ExposedTableID int64
	Limit          int64
	Offset         int64
}

func (q *Queries) ListUploadJobsByTable(ctx context.Context, arg ListUploadJobsByTableParams) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listUploadJobsByTable, arg.ExposedTableID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.Filename,
			&i.RowCount,
			&i.Status,
			&i.ErrorMessage,
			&i.MappingConfig,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadJobsByUser = `-- name: ListUploadJobsByUser :many
SELECT id, user_id, exposed_table_id, filename, row_count, status, error_message, mapping_config, created_at, completed_at
FROM upload_jobs
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUploadJobsByUserParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListUploadJobsByUser(ctx context.Context, arg ListUploadJobsByUserParams) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listUploadJobsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.Filename,
			&i.RowCount,
			&i.Status,
			&i.ErrorMessage,
			&i.MappingConfig,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadJobStatus = `-- name: UpdateUploadJobStatus :exec
UPDATE upload_jobs
SET 
    status = ?,
    error_message = ?
WHERE id = ?
`

type UpdateUploadJobStatusParams struct {
	Status       string
	ErrorMessage sql.NullString
	ID           int64
}

func (q *Queries) UpdateUploadJobStatus(ctx context.Context, arg UpdateUploadJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadJobStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
