// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package store

import (
	"context"
	"database/sql"
)

const createUserPreference = `-- name: CreateUserPreference :one

INSERT INTO user_preferences (
    user_id,
    exposed_table_id,
    preference_key,
    preference_value
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, user_id, exposed_table_id, preference_key, preference_value, created_at, updated_at
`

type CreateUserPreferenceParams struct {
	UserID          int64
	ExposedTableID  sql.NullInt64
	PreferenceKey   string
	PreferenceValue string
}

// User Preferences queries
func (q *Queries) CreateUserPreference(ctx context.Context, arg CreateUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, createUserPreference,
		arg.UserID,
		arg.ExposedTableID,
		arg.PreferenceKey,
		arg.PreferenceValue,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.PreferenceKey,
		&i.PreferenceValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_preferences
WHERE user_id = ? AND exposed_table_id = ? AND preference_key = ?
`

type DeleteUserPreferenceParams struct {
	UserID         int64
	ExposedTableID sql.NullInt64
	PreferenceKey  string
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserPreference, arg.UserID, arg.ExposedTableID, arg.PreferenceKey)
	return err
}

const deleteUserPreferencesByTable = `-- name: DeleteUserPreferencesByTable :exec
DELETE FROM user_preferences
WHERE exposed_table_id = ?
`

func (q *Queries) DeleteUserPreferencesByTable(ctx context.Context, exposedTableID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPreferencesByTable, exposedTableID)
	return err
}

const deleteUserPreferencesByUser = `-- name: DeleteUserPreferencesByUser :exec
DELETE FROM user_preferences
WHERE user_id = ?
`

func (q *Queries) DeleteUserPreferencesByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPreferencesByUser, userID)
	return err
}

const getUserPreference = `-- name: GetUserPreference :one
SELECT id, user_id, exposed_table_id, preference_key, preference_value, created_at, updated_at
FROM user_preferences
WHERE user_id = ? AND exposed_table_id = ? AND preference_key = ?
LIMIT 1
`

type GetUserPreferenceParams struct {
	UserID         int64
	ExposedTableID sql.NullInt64
	PreferenceKey  string
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreference, arg.UserID, arg.ExposedTableID, arg.PreferenceKey)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.PreferenceKey,
		&i.PreferenceValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserPreferencesByTable = `-- name: ListUserPreferencesByTable :many
SELECT id, user_id, exposed_table_id, preference_key, preference_value, created_at, updated_at
FROM user_preferences
WHERE user_id = ? AND exposed_table_id = ?
ORDER BY preference_key
`

type ListUserPreferencesByTableParams struct {
	UserID         int64
	ExposedTableID sql.NullInt64
}

func (q *Queries) ListUserPreferencesByTable(ctx context.Context, arg ListUserPreferencesByTableParams) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listUserPreferencesByTable, arg.UserID, arg.ExposedTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.PreferenceKey,
			&i.PreferenceValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPreferencesByUser = `-- name: ListUserPreferencesByUser :many
SELECT id, user_id, exposed_table_id, preference_key, preference_value, created_at, updated_at
FROM user_preferences
WHERE user_id = ?
ORDER BY preference_key
`

func (q *Queries) ListUserPreferencesByUser(ctx context.Context, userID int64) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listUserPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExposedTableID,
			&i.PreferenceKey,
			&i.PreferenceValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPreference = `-- name: UpdateUserPreference :one
UPDATE user_preferences
SET preference_value = ?
WHERE user_id = ? AND exposed_table_id = ? AND preference_key = ?
RETURNING id, user_id, exposed_table_id, preference_key, preference_value, created_at, updated_at
`

type UpdateUserPreferenceParams struct {
	PreferenceValue string
	UserID          int64
	ExposedTableID  sql.NullInt64
	PreferenceKey   string
}

func (q *Queries) UpdateUserPreference(ctx context.Context, arg UpdateUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, updateUserPreference,
		arg.PreferenceValue,
		arg.UserID,
		arg.ExposedTableID,
		arg.PreferenceKey,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExposedTableID,
		&i.PreferenceKey,
		&i.PreferenceValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
