// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    display_name,
    hashed_password,
    sso_provider,
    sso_id,
    is_active,
    is_admin
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Email          string
	Username       string
	DisplayName    string
	HashedPassword sql.NullString
	SsoProvider    sql.NullString
	SsoID          sql.NullString
	IsActive       int64
	IsAdmin        int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.HashedPassword,
		arg.SsoProvider,
		arg.SsoID,
		arg.IsActive,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.SsoProvider,
		&i.SsoID,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many

SELECT id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
FROM users
`

// Users queries
func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.HashedPassword,
			&i.SsoProvider,
			&i.SsoID,
			&i.IsActive,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.SsoProvider,
		&i.SsoID,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.SsoProvider,
		&i.SsoID,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserBySSO = `-- name: GetUserBySSO :one
SELECT id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
FROM users
WHERE sso_provider = ? AND sso_id = ?
LIMIT 1
`

type GetUserBySSOParams struct {
	SsoProvider sql.NullString
	SsoID       sql.NullString
}

func (q *Queries) GetUserBySSO(ctx context.Context, arg GetUserBySSOParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySSO, arg.SsoProvider, arg.SsoID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.SsoProvider,
		&i.SsoID,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.SsoProvider,
		&i.SsoID,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    email = ?,
    username = ?,
    display_name = ?,
    is_active = ?,
    is_admin = ?
WHERE id = ?
RETURNING id, email, username, display_name, hashed_password, sso_provider, sso_id, is_active, is_admin, created_at, updated_at, last_login_at
`

type UpdateUserParams struct {
	Email       string
	Username    string
	DisplayName string
	IsActive    int64
	IsAdmin     int64
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.IsActive,
		arg.IsAdmin,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.HashedPassword,
		&i.SsoProvider,
		&i.SsoID,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	HashedPassword sql.NullString
	ID             int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.HashedPassword, arg.ID)
	return err
}
