// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "northstar/internal/features/common/layouts"
import "northstar/internal/features/explorer/components"

var schemas = []components.Schema{
	{
		Name:       "auth",
		TableCount: 2,
		Tables: []components.Table{
			{Name: "sso_domains", IsActive: false},
			{Name: "users", IsActive: false},
		},
	},
	{
		Name:       "public",
		TableCount: 2,
		Tables: []components.Table{
			{Name: "test", IsActive: true}, // This table is currently selected
			{Name: "products", IsActive: false},
		},
	},
}

var breadcrumbsData = []components.BreadcrumbItem{
	{Name: "postgres_catalog", Href: "/"},
	{Name: "public"},
	{Name: "gaaay"},
}

// 2. Table Data View
var tableData = components.TableData{
	Headers: []string{"id", "name", "created_at", "status", "value"},
	Rows: [][]any{
		{1, "First Item", "2023-10-27T10:00:00Z", "active", 105.99},
		{2, "Second Item", "2023-10-27T11:00:00Z", "inactive", 250.00},
		{3, "Third Item", "2023-10-28T12:30:00Z", "pending", 99.50},
	},
}

// 3. Columns View Data
var columnsData = []components.ColumnInfo{
	{
		Name:         "id",
		DataType:     "integer",
		IsNullable:   false,
		DefaultValue: "nextval('test_id_seq')",
	},
	{
		Name:         "name",
		DataType:     "character varying(255)",
		IsNullable:   true,
		DefaultValue: "NULL",
	},
	{
		Name:         "created_at",
		DataType:     "timestamp with time zone",
		IsNullable:   false,
		DefaultValue: "now()",
	},
	{
		Name:         "status",
		DataType:     "character varying(50)",
		IsNullable:   true,
		DefaultValue: "'active'::character varying",
	},
	{
		Name:         "value",
		DataType:     "numeric(10,2)",
		IsNullable:   true,
		DefaultValue: "NULL",
	},
}

// 4. Details View Data
var detailsData = components.TableDetails{
	Owner:              "postgres",
	RowSecurityEnabled: false,
	EstimatedRows:      2,
	CreatedAt:          "2023-01-01 12:00:00 UTC",
}

var mainContentParams = components.MainContentParams{
	Breadcrumbs:  breadcrumbsData,
	TableData:    tableData,
	Columns:      columnsData,
	TableDetails: detailsData,
}

func ExplorerPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"table-explorer-component\" class=\"flex h-screen font-sans\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Sidebar(schemas).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.MainContent(mainContentParams).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppShell("Unity Explorer - test").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
